# ----------- CONFIGURABLE START -----------
title: "LiberXue|FullStack|独立开发者|jekyll blog|GitHub blog"
description: "Full Stack独立开发者|欢迎来到 LiberXue「角落」侃侃理想、谈谈人生、敲敲代码。"
url: https://opadougie.github.io # 域名
signoff: "LiberXue" # Your name
facebook_appid: #liberxue
google_analytics: UA-101222464-1
share: true
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name: 首页 home
    url: /
    external: false
  - name: 书籍 books
    url: /book
    external: false
  - name: 旅游 road
    url: /road
    external: false
  - name: 归档 archives
    url: /archives
    external: false
  - name: 标签 tags
    url: /tags
    external: false
  - name: 关于 about
    url: /about
    external: false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
